name: GitHub Pages
run-name: ${{ github.actor }} is rolling out a new version of the app 🚀
on: [push]
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install npm deps
      working-directory: ./react-chat
      run: npm i
    - name: Set environment variables
      env:
        VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
      run: |
        echo "VITE_WS_URL=$VITE_WS_URL" >> ./react-chat/.env
        echo "VITE_API_URL=$VITE_API_URL" >> ./react-chat/.env
    - name: Build app
      working-directory: ./react-chat
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./react-chat/dist